### ISSUE TITLE
[FEATURE REQUEST]: A Checkbox for sticky persona's information in the prompt

### ISSUE THREAD

**Issue by ahmed-elj** [SillyTavern/Extension-QuickPersona#1]
I suggest that you add a checkbox for each persona in the dropdown menu, to preserve their information in the prompt.
(sticky persona)

---

Why?
So that the AI can differentiate between each persona without missing their information after a switch.

**Comment by Cohee1207** [comment]
If anything, I don't think it belongs to this extension. If you require this, I suggest storing persona descriptions in World Info / Lorebooks.

**Comment by ahmed-elj** [comment]
yeah, that's a good workaround solution, thanks anyway.
